cafetering_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cafetering_app import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'cafetering_app'

urlpatterns = [
    url(r'^$', views.login_view, name='login_view'),
    url(r'^login$', views.login_view, name='login_view'),
    url(r'^reset_password$', views.reset_password_view, name='reset_password_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^index$', views.index, name='index'),
    url(r'^pedidos$', views.pedidos_view, name='pedidos_view'),

    url(r'^(?i)ver-pedido/(?P<pedido_pk>[0-9]+)/$', views.pedido_view, name='pedido_view'),
    url(r'^(?i)ver-oferta/(?P<oferta_pk>[0-9]+)/$', views.oferta_view, name='oferta_view'),
    url(r'^(?i)ver-menu/(?P<menu_pk>[0-9]+)/$', views.menu_view, name='menu_view'),
    url(r'^(?i)ver-categoria/(?P<categoria_pk>[0-9]+)/$', views.categoria_view, name='categoria_view'),
    url(r'^(?i)ver-producto/(?P<producto_pk>[0-9]+)/$', views.producto_view, name='producto_view'),

    url(r'^nueva-oferta/?$', views.nueva_oferta_view, name='nueva_oferta_view'),
    url(r'^nuevo-menu/?$', views.nuevo_menu_view, name='nuevo_menu_view'),
    url(r'^nueva-categoria/?$', views.nueva_categoria_view, name='nueva_categoria_view'),
    url(r'^nuevo-producto/?$', views.nuevo_producto_view, name='nuevo_producto_view'),

    url(r'^editar-pedido/(?P<pedido_pk>[0-9]+)/$', views.editar_pedido_view, name='editar_pedido_view'),
    url(r'^editar-oferta/(?P<oferta_pk>[0-9]+)/$', views.editar_oferta_view, name='editar_oferta_view'),
    url(r'^editar-menu/(?P<menu_pk>[0-9]+)/$', views.editar_menu_view, name='editar_menu_view'),
    url(r'^editar-producto/(?P<producto_pk>[0-9]+)/$', views.editar_producto_view, name='editar_producto_view'),
    url(r'^editar-categoria/(?P<categoria_pk>[0-9]+)/$', views.editar_categoria_view, name='editar_categoria_view'),

    url(r'^eliminar-pedido/(?P<pedido_pk>[0-9]+)/?$', views.eliminar_pedido_view, name='eliminar_pedido_view'),
    url(r'^eliminar-oferta/(?P<oferta_pk>[0-9]+)/?$', views.eliminar_oferta_view, name='eliminar_oferta_view'),
    url(r'^eliminar-menu/(?P<menu_pk>[0-9]+)/?$', views.eliminar_menu_view, name='eliminar_menu_view'),
    url(r'^eliminar-producto/(?P<producto_pk>[0-9]+)/?$', views.eliminar_producto_view, name='eliminar_producto_view'),
    url(r'^eliminar-categoria/(?P<categoria_pk>[0-9]+)/?$', views.eliminar_categoria_view,
        name='eliminar_categoria_view'),

    url(r'^ofertas$', views.ofertas_view, name='ofertas_view'),
    url(r'^menus$', views.menus_view, name='menus_view'),
    url(r'^productos$', views.productos_view, name='productos_view'),
    url(r'^categorias$', views.categorias_view, name='categorias_view'),
    url(r'^logout$', views.logout_view, name='logout_view'),
    url(r'^cuenta$', views.cuenta_view, name='cuenta_view'),
    url(r'^informes$', views.informes_view, name='informes_view'),
    url(r'^ayuda$', views.ayuda_view, name='ayuda_view'),
    url(r'^buscar$', views.buscar_view, name='buscar_view'),

    url(r'^pedido-preparado/(?P<pedido_pk>[0-9]+)/?$', views.pedido_preparado_view, name='pedido_preparado_view'),
    url(r'^pedido-recogido/(?P<pedido_pk>[0-9]+)/?$', views.pedido_recogido_view, name='pedido_recogido_view'),
    url(r'^pedido-norecogido/(?P<pedido_pk>[0-9]+)/?$', views.pedido_no_recogido_view, name='pedido_no_recogido_view'),
    url(r'^test$', views.test_view, name='test_view'),

    url(r'^ajax/autocomplete_id_producto/$', views.autocomplete_id_producto, name='autocomplete_id_producto'),
    url(r'^ajax/autocomplete_nombre_producto/$', views.autocomplete_nombre_producto,
        name='autocomplete_nombre_producto'),
    url(r'^ajax/autocomplete_oferta/$', views.autocomplete_oferta_view, name='autocomplete_oferta_view'),
    url(r'^ajax/autocomplete_menu/$', views.autocomplete_menu_view, name='autocomplete_menu_view'),
    url(r'^ajax/autocomplete_nombre_alergeno/$', views.autocomplete_alergeno_view, name='autocomplete_alergeno_view'),
    url(r'^ajax/autocomplete_nombre_etiqueta/$', views.autocomplete_etiqueta_view, name='autocomplete_etiqueta_view'),
    url(r'^ajax/remove_product_from_list/$', views.remove_product_from_list, name='remove_product_from_list'),
    url(r'^ajax/reset_password/$', views.reset_password, name='reset_password'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django_fsm import FSMField, transition
from django.core.validators import RegexValidator
from django_fsm_log.decorators import fsm_log_by

ESTADO_CHOICES = (
    (0, 'Inactivo'),
    (1, 'Activo'),
)


class Universidad(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    ciudad = models.CharField(max_length=30)


class Cafeteria(models.Model):
    id = models.AutoField(primary_key=True)
    facultad = models.CharField(max_length=30)
    universidad = models.ForeignKey(Universidad, on_delete=models.CASCADE)


class Alumno(models.Model):
    id = models.AutoField(primary_key=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="El telefono debe tener el formato: '+999999999'. Maximo 15 digitos.")
    telefono = models.CharField(validators=[phone_regex], max_length=17, blank=True,
                                null=True)
    fecha_nacimiento = models.DateField()
    universidad = models.ForeignKey(Universidad, on_delete=models.CASCADE)
    cafeteria = models.ForeignKey(Cafeteria, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Empleado(models.Model):
    TIPO_EMPLEADOS = ((1, "Encargado"),
                      (2, "Camarero"),)
    id = models.AutoField(primary_key=True)
    cafeteria = models.ManyToManyField(Cafeteria, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_empleado = models.IntegerField(choices=TIPO_EMPLEADOS,
                                        default=2)


class Etiqueta(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    imagen = models.ImageField(upload_to='etiquetas/', null=True, blank=True)


class Alergeno(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    imagen = models.ImageField(upload_to='alergenos/', null=True, blank=True)


class Producto(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    calorias = models.FloatField(null=True, blank=True)
    grasas_saturadas = models.FloatField(null=True, blank=True)
    precio = models.FloatField()
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    imagen = models.ImageField(null=True, blank=True, upload_to='productos/')
    etiquetas = models.ManyToManyField(Etiqueta, blank=True)
    alergenos = models.ManyToManyField(Alergeno, blank=True)
    precio_oferta = models.FloatField(null=True, blank=True, default=0.0)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    estado = models.IntegerField(default=0, choices=ESTADO_CHOICES)
    cafeteria = models.ForeignKey(Cafeteria, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "<Producto #%d; %s>" % (self.id, self.nombre)

class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    productos = models.ManyToManyField(Producto)
    estado = models.IntegerField(default=0, choices=ESTADO_CHOICES)
    imagen = models.ImageField(upload_to='categoria/', null=True, blank=True)
    cafeteria = models.ForeignKey(Cafeteria, on_delete=models.CASCADE, null=True)


class Resena(models.Model):
    id = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    comentario = models.CharField(max_length=400, null=True, blank=True)
    calificacion = models.IntegerField(null=True, blank=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)


class Oferta(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    descuento_porcentual = models.IntegerField(null=True, blank=True)
    descuento_numerico = models.FloatField(null=True, blank=True)
    productos = models.ManyToManyField(Producto, through='OfertaProducto')
    imagen = models.ImageField(upload_to='oferta/', null=True, blank=True)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    estado = models.IntegerField(default=0, choices=ESTADO_CHOICES)
    valido_desde = models.DateTimeField(default=timezone.now)
    valido_hasta = models.DateField(null=True, blank=True)
    precio_oferta = models.FloatField(null=True, blank=True)
    cafeteria = models.ForeignKey(Cafeteria, on_delete=models.CASCADE, null=True)

    def setPrecioOferta(self):
        for product in self.ofertaproducto_set.all():
            if self.descuento_porcentual:
                product.precio_oferta = product.producto.precio * (1 - (float(self.descuento_porcentual) / 100))
            elif self.descuento_numerico:
                product.precio_oferta = 0
            else:
                raise ValueError('Offer does not have discount set for PRODUCT ID %d' % producto.id)
            product.save()

    def save(self, *args, **kwargs):
        super(Oferta, self).save(*args, **kwargs)
        from django.db.models import Sum
        if self.descuento_porcentual or self.descuento_numerico:
            self.setPrecioOferta()
            if not self.precio_oferta:
                self.precio_oferta = self.productos.aggregate(Sum('precio_oferta'))['precio_oferta__sum']
                super(Oferta, self).save(*args, **kwargs)


class Menu(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    productos = models.ManyToManyField(Producto, through='MenuProducto')
    estado = models.IntegerField(default=0, choices=ESTADO_CHOICES)
    imagen = models.ImageField(upload_to='menu/', null=True, blank=True)
    precio = models.FloatField(null=True, blank=True)
    valido_hasta = models.DateField(null=True, blank=True)
    cafeteria = models.ForeignKey(Cafeteria, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "<Menu: %s>" % self.nombre


STATES_STR = ('En cola', 'En proceso', 'Preparado', 'Entregado', 'No recogido', 'Cancelado')
STATES = list(zip(STATES_STR, STATES_STR))


class Pedido(models.Model):
    id = models.AutoField(primary_key=True)
    estado = FSMField(default=STATES[0], choices=STATES)
    productos = models.ManyToManyField(Producto, through='ProductoPedido')
    menus = models.ManyToManyField(Menu, through='MenuPedido')
    ofertas = models.ManyToManyField(Oferta, through='OfertaPedido')
    fecha_creacion = models.DateTimeField(default=timezone.now)
    recogida_estimada = models.DateTimeField()
    fecha_recogida = models.DateTimeField(null=True, blank=True)
    qr = models.ImageField(upload_to='qr/', null=True, blank=True)
    ordenante = models.ManyToManyField(Alumno, related_name='alumnos')
    resenas = models.ManyToManyField(Resena, blank=True)
    importe = models.FloatField(null=True, blank=True)
    codigo_confirmacion = models.CharField(unique=True, null=True, blank=True, max_length=10)
    observaciones = models.CharField(max_length=60, null=True, blank=True)
    cafeteria = models.ForeignKey(Cafeteria, on_delete=models.CASCADE, null=True)

    def set_estado(self, new_estado, user):
        if new_estado == u"Entregado":
            self.recogido(by=user)
            self.fecha_recogida = timezone.now()
        elif new_estado == u"Cancelado":
            self.cancelar(by=user)
        elif new_estado == u"En cola":
            self.en_cola(by=user)
        elif self.estado == u"En cola" and new_estado == u"En proceso":
            self.preparando(by=user)
        elif self.estado == u"En proceso" and new_estado == u"Preparado":
            self.preparado(by=user)
        elif self.estado == u"Preparado" and new_estado == u"No recogido":
            self.no_recogido(by=user)
        else:
            self.estado = new_estado

    @property
    def hasResena(self):
        return self.resenas.exists()

    @property
    def importe_productos(self):
        productos = self.productopedido_set.all()
        total = 0.0
        for producto in productos:
            total += producto.subtotal
        return total

    @property
    def importe_ofertas(self):
        ofertas = self.ofertapedido_set.all()
        total = 0.0
        for oferta in ofertas:
            total += oferta.subtotal
        return total

    @property
    def importe_menus(self):
        menus = self.menupedido_set.all()
        total = 0.0
        for menu in menus:
            total += menu.subtotal
        return total

    @property
    def generate_confirmation_code(self):
        import string
        import random
        code = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5))
        while Pedido.objects.filter(codigo_confirmacion=code):
            code = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5))
        return code

    @property
    def importe_total(self):
        return self.importe_productos + self.importe_ofertas + self.importe_menus

    def __str__(self):
        return "<Pedido %d; %s>" % (self.id, self.get_estado_display())

    def save(self, *args, **kwargs):
        self.importe = self.importe_total
        if not self.codigo_confirmacion:
            self.codigo_confirmacion = self.generate_confirmation_code

        super(Pedido, self).save(*args, **kwargs)

        if not self.qr:
            import qrcode
            from StringIO import StringIO
            from django.core.files.uploadedfile import InMemoryUploadedFile

templates/account.html
{% extends 'base.html' %}
{% block content %}

    <!-- Main Content -->
    <div class="page-container" id="PageContainer">
        <main class="main-content" id="MainContent" role="main">
            <section class="heading-content">
                <div class="heading-wrapper">
                    <div class="container">
                        <div class="row">
                            <div class="page-heading-inner heading-group">
                                <div class="breadcrumb-group">
                                    <h1 class="hidden">Mi cuenta</h1>
                                    <div class="breadcrumb clearfix">
										<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a
                                                href="./index" title="Fast Food" itemprop="url"><span
                                                itemprop="title"><i class="fa fa-home"></i></span></a>
										</span>
                                        <span class="arrow-space"></span>
										<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
											<a href="./cuenta" title="Mi cuenta" itemprop="url"><span
                                                    itemprop="title">Mi cuenta</span></a>
										</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="account-layout">
                <div class="account-wrapper">
                    <div class="container">
                        <div class="row">
                            <div class="account-inner">
                                <div class="account-content">
                                    <div class="account-info">
                                        <div class="account-details col-sm-6">
                                            <h3 class="details-title">Detalles de su cuenta</h3>
                                            <div class="details-content">
                                                <div class="details-item name">
                                                    <span class="title">Nombre:</span>
                                                    <span class="content">{{ user.get_full_name }}</span>
                                                </div>
                                                <div class="details-item">
                                                    <span class="title">E-mail:</span>
                                                    <a class="content">{{ user.email }}</a>
                                                </div>
                                                <div class="details-item">
                                                    <span class="title">Facultad</span>
                                                    {% for cafeteria in cafeterias %}
                                                        <address class="content">{{ cafeteria.facultad }}. {{ cafeteria.universidad.nombre }}</address>
                                                    {% endfor %}
                                                </div>
                                                <div class="details-item">
                                                    <span class="title">Rol</span>
                                                    <a class="content">{{ empleado.get_tipo_empleado_display }}</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="account-link col-sm-6">

                                            <h3 class="link-title" align="center">Acciones</h3>
                                            <div class="link-content" align="center">
                                                <button class="btn btn-default" onclick="$(this).sendPasswordEmail();">Regenerar contraseña</button>
                                                <br><br>
                                                <button class="btn btn-default" onclick="location.href='mailto:modificaciones@cafetering.es'" >Requirir modificación</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    </div>
<script>
        $.fn.sendPasswordEmail = function () {
            $.ajax({
                url: "/ajax/reset_password",
                dataType: 'json',
                success: function (data) {
                    alert("Mensaje enviado correctamente");
                }
            });
        };

</script>
{% endblock content %}

templates/buscar.html
{% extends 'base.html' %}
{% load main_tags %}
{% block content %}

	<!-- Main Content -->
	<div class="page-container" id="PageContainer">
		<main class="main-content" id="MainContent" role="main">
			<section class="heading-content">
				<div class="heading-wrapper">
					<div class="container">
						<div class="row">
							<div class="page-heading-inner heading-group">
								<div class="breadcrumb-group">
									<h1 class="hidden">Buscar</h1>
									<div class="breadcrumb clearfix">
										<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="./index" title="Buscar" itemprop="url"><span itemprop="title"><i class="fa fa-home"></i></span></a>
										</span>
										<span class="arrow-space"></span>
										<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
											<a href="./buscar" title="Search Page" itemprop="url"><span itemprop="title">Buscar</span></a>
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<section class="search-content">
				<div class="search-content-wrapper">
					<div class="container">
						<div class="row">
							<div class="search-content-group">
								<div class="search-content-inner">
									<div id="search">
										<div class="expanded-message">
											<div class="search-field">
												<form method="post" class="search" style="position: relative;">{% csrf_token %}
													<input type="hidden" name="type" value="product">
													<button class="search-submit" type="submit">
														<span class="cs-icon icon-search"></span>
													</button>
													<input type="text" name="search_term_form" class="search_box" placeholder="Introduzca su busqueda" value="{{ search_term }}" autocomplete="off">
												</form>
											</div>
										</div>
                                        {% if result_list %}
                                            <!-- Begin results -->
                                            <div class="product-item-group clearfix">
                                                <div class="product-item-inner">
                                                    {% for objeto in result_list %}
                                                        {% with objeto|classname as modelclass %}
                                                            {% if modelclass == "Pedido" %}
                                                                <div class="product-item-wrapper col-sm-3">
                                                                    <div class="row-container product list-unstyled clearfix product-circle">
                                                                        <div class="row-left">
                                                                            <a href="/ver-{{ modelclass }}/{{ objeto.id }}" class="hoverBorder container_item">
                                                                                <div class="hoverBorderWrapper">
                                                                                    <img src="static/images/pedido_icono.jpg" class="img-responsive front" alt="Pedido">
                                                                                    <div class="mask"></div>
                                                                                </div>
                                                                            </a>
                                                                        </div>
                                                                        <div class="row-right animMix">
                                                                            <div class="product-title"><a class="title-5" href="./ver-{{ modelclass }}/{{ objeto.id }}">{{ modelclass }} #{{ objeto.id }}</a></div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            {% else %}
                                                                <div class="product-item-wrapper col-sm-3">
                                                                    <div class="row-container product list-unstyled clearfix product-circle">
                                                                        <div class="row-left">
                                                                            <a href="/ver-{{ modelclass }}/{{ objeto.id }}" class="hoverBorder container_item">
                                                                                <div class="hoverBorderWrapper">
                                                                                    {% if objeto.imagen %}
                                                                                        <img src="{{ objeto.imagen.url }}" class="img-responsive front" alt="">
                                                                                    {% else %}
                                                                                        <img src="static/images/no_image_available.png" class="img-responsive front" alt="">
                                                                                    {% endif %}
                                                                                </div>
                                                                            </a>
                                                                        </div>
                                                                        <div class="row-right animMix">
                                                                            <div class="product-title"><a class="title-5" href="./ver-{{ modelclass }}/{{ objeto.id }}">{{ modelclass }} #{{ objeto.id }}</a></div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                            {% endif %}
                                                        {% endwith %}
                                                    {% endfor %}
                                                </div>
                                            </div>
                                            <!-- End results -->
                                            <div class="search-bottom-toolbar">
                                                <div class="search-pagination col-sm-6">

                                                </div>
                                            </div>
                                        {% endif%}
									</div>
									<!-- /#search -->
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</main>
	</div>
	
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block content %}

	<!-- Main Content -->
	<div class="page-container" id="PageContainer">
		<main class="main-content" id="MainContent" role="main">
			<section class="customers-layout login-layout">
				<div class="customers-wrapper">
					<div class="container">
						<div class="row">
							<div class="customers-inner">
								<div class="customers-content">
									<div id="login" class="customers">
										<h2>Login</h2>
										<form method="post" accept-charset="UTF-8"> {% csrf_token %}
                                            {% if login_incorrect %}
                                                <p class="message">El usuario o la contraseña no son correctas</p>
                                            {% endif %}
											<div class="clearfix large_form form-item">
												<input type="text" value="" placeholder="Usuario" name="customer[username]" id="customer_username" class="text">
											</div>
											<div class="clearfix large_form form-item form-password">
												<input type="password" value="" placeholder="Contraseña" name="customer[password]" id="customer_password" class="text" size="16">
												<span class="cs-icon icon-eye"></span>
											</div>
											<div class="clearfix">
												<a class="note" href="#" onclick="showRecoverPasswordForm();return false;">¿Has olvidado la contraseña?</a>
											</div>
											<div class="action_bottom">
												<input class="_btn" name="action" type="submit" value="Entrar">
                                                <input class="_btn" name="action" type="submit" value="Test Login">
											</div>
										</form>
										<div class="create-account">
											<h4>¿Aún no tienes una cuenta?</h4>
											<a href="mailto:peticiones@cafetering.es" class="_btn">Contáctanos</a>
										</div>
									</div>
									<div id="recover-password" style="display:none;" class="customers">
										<h2>Reset Password</h2>
										<p class="note">We will send you an email to reset your password.</p>
										<form method="post" action="./reset_password" accept-charset="UTF-8"> {% csrf_token %}
											<div class="clearfix large_form form-item">
												<input type="email" value="" placeholder="Email Address" size="30" name="email" id="recover-email" class="text">
											</div>
											<div class="action_bottom clearfix">
												<input class="_btn" type="submit" value="Login">
											</div>
											<div class="clearfix note_text_group">
												or<span class="note_link"><a href="#" onclick="hideRecoverPasswordForm();return false;">Cancel</a></span>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<script type="text/javascript">
				function showRecoverPasswordForm() {
					document.getElementById('recover-password').style.display = 'block';
					document.getElementById('login').style.display = 'none';
				}

				function hideRecoverPasswordForm() {
					document.getElementById('recover-password').style.display = 'none';
					document.getElementById('login').style.display = 'block';
				}

				if (window.location.hash == '#recover') {
					showRecoverPasswordForm()
				}
			</script>
		</main>
	</div>
	
{% endblock content %}